#pragma once

namespace SimpleEngine
{

enum InputKey
{
    KB_UNKNOWN = 0,

    /*
     * Keyboard keys
     */

    KB_BACKSPACE = '\b',
    KB_TAB = '\t',
    KB_RETURN = '\r',
    KB_ESCAPE = '\x1B',
    KB_SPACE = ' ',
    KB_EXCLAIM = '!',
    KB_QUOTEDBL = '"',
    KB_HASH = '#',
    KB_DOLLAR = '$',
    KB_PERCENT = '%',
    KB_AMPERSAND = '&',
    KB_QUOTE = '\'',
    KB_LEFTPAREN = '(',
    KB_RIGHTPAREN = ')',
    KB_ASTERISK = '*',
    KB_PLUS = '+',
    KB_COMMA = ',',
    KB_MINUS = '-',
    KB_PERIOD = '.',
    KB_SLASH = '/',
    KB_0 = '0',
    KB_1 = '1',
    KB_2 = '2',
    KB_3 = '3',
    KB_4 = '4',
    KB_5 = '5',
    KB_6 = '6',
    KB_7 = '7',
    KB_8 = '8',
    KB_9 = '9',
    KB_COLON = ':',
    KB_SEMICOLON = ';',
    KB_LESS = '<',
    KB_EQUALS = '=',
    KB_GREATER = '>',
    KB_QUESTION = '?',
    KB_AT = '@',

    KB_LEFTBRACKET = '[',
    KB_BACKSLASH = '\\',
    KB_RIGHTBRACKET = ']',
    KB_CARET = '^',
    KB_UNDERSCORE = '_',
    KB_BACKQUOTE = '`',
    KB_a = 'a',
    KB_b = 'b',
    KB_c = 'c',
    KB_d = 'd',
    KB_e = 'e',
    KB_f = 'f',
    KB_g = 'g',
    KB_h = 'h',
    KB_i = 'i',
    KB_j = 'j',
    KB_k = 'k',
    KB_l = 'l',
    KB_m = 'm',
    KB_n = 'n',
    KB_o = 'o',
    KB_p = 'p',
    KB_q = 'q',
    KB_r = 'r',
    KB_s = 's',
    KB_t = 't',
    KB_u = 'u',
    KB_v = 'v',
    KB_w = 'w',
    KB_x = 'x',
    KB_y = 'y',
    KB_z = 'z',

    KB_DELETE = '\x7F',

    // Special Keys
    KB_CAPSLOCK = 300,
    KB_F1,
    KB_F2,
    KB_F3,
    KB_F4,
    KB_F5,
    KB_F6,
    KB_F7,
    KB_F8,
    KB_F9,
    KB_F10,
    KB_F11,
    KB_F12,

    KB_PRINTSCREEN,
    KB_SCROLLLOCK,
    KB_PAUSE,
    KB_INSERT,
    KB_HOME,
    KB_PAGEUP,
    KB_END,
    KB_PAGEDOWN,
    KB_RIGHT = 321,
    KB_LEFT,
    KB_DOWN,
    KB_UP,

    KB_NUMLOCKCLEAR,
    KB_KP_DIVIDE,
    KB_KP_MULTIPLY,
    KB_KP_MINUS,
    KB_KP_PLUS,
    KB_KP_ENTER,
    KB_KP_1,
    KB_KP_2,
    KB_KP_3,
    KB_KP_4,
    KB_KP_5,
    KB_KP_6,
    KB_KP_7,
    KB_KP_8,
    KB_KP_9,
    KB_KP_0,
    KB_KP_PERIOD,

    // Modifier Keys
    KB_LCTRL,
    KB_LSHIFT,
    KB_LALT,
    KB_LGUI,
    KB_RCTRL,
    KB_RSHIFT,
    KB_RALT,
    KB_RGUI,

    /*
     * Mouse
     */
    M_LEFT = 1001,
    M_MIDDLE,
    M_RIGHT,
    M_B4,
    M_B5
};

}  // namespace SimpleEngine